# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74813cf26e1791e147c8b25847be680d9d2ce52bedaefe2d28adc0deb680d78d14961cd27a5d7a93814bb6081e871a4f20e0f4d125f248d5136478974dc7e57

test:
  secret_key_base: b65202dcae34748fbb7eb81eb3f9123cc1718705254eef2a339d97ba7898278c5e119f2885829a29becd9111c1a667571f009c6489dde898bc82b7830cdbe663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
